# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170628_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
    ]
