# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-30 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_click_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u56fe\u7247\u540d\u5b57')),
                ('image', models.ImageField(upload_to='/images/%Y/%m', verbose_name='\u56fe\u7247\u5730\u5740')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='\u6240\u5c5e\u6587\u7ae0')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '\u56fe\u7247\u5e93',
                'verbose_name_plural': '\u56fe\u7247\u5e93',
            },
        ),
    ]
