# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('email', models.EmailField(max_length=255, verbose_name='\u7535\u5b50\u90ae\u4ef6')),
                ('subject', models.CharField(max_length=20, verbose_name='\u4e3b\u9898')),
                ('text', models.TextField(verbose_name='\u7559\u8a00\u4fe1\u606f')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u7559\u8a00\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
    ]
