# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-30 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '\u7559\u8a00', 'verbose_name_plural': '\u7559\u8a00'},
        ),
    ]
