# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-02 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170630_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(verbose_name='\u7ad9\u70b9'),
        ),
    ]
